-- Module 6 catalog extension for Lessons 6.6 (Polynomial Workshop challenge)
-- and 6.7 (Polynomial Playground sandbox).
--
-- Additive follow-up to 202609110002_module6_lessons_catalog.sql, which is
-- already applied: it holds the module's original lessons, and this one adds
-- the challenge and sandbox lessons that came later. Both are rerunnable, so
-- applying either twice is harmless.
--
-- Requires 202608120001_account_progress.sql.

BEGIN;

DO $$
BEGIN
  IF to_regclass('public.learning_step_catalog') IS NULL THEN
    RAISE EXCEPTION
      'public.learning_step_catalog is required; apply 202608120001 first';
  END IF;

  IF to_regprocedure(
    'public.record_lesson_step(text,text,text,integer,boolean,integer)'
  ) IS NULL THEN
    RAISE EXCEPTION
      'public.record_lesson_step is required; apply 202608120001 first';
  END IF;
END;
$$;

-- Prevent concurrent catalog migrations from interleaving validation.
LOCK TABLE public.learning_step_catalog IN SHARE ROW EXCLUSIVE MODE;

-- Generated by tool/generate_module_catalog_sql.dart from lib/data/module6/ so
-- the catalog cannot drift from the shipped lesson content.
INSERT INTO public.learning_step_catalog (
  module_id,
  lesson_id,
  step_id,
  content_version,
  step_index,
  is_answer_step,
  xp_reward,
  is_final
)
VALUES
  -- Lesson 6.6: Module 6 Challenge (12 steps)
  ('module6', 'm6_l6', 'm6_l6_s01', 1, 0, FALSE, 0, FALSE),
  ('module6', 'm6_l6', 'm6_l6_s02', 1, 1, TRUE, 0, FALSE),
  ('module6', 'm6_l6', 'm6_l6_s03', 1, 2, TRUE, 0, FALSE),
  ('module6', 'm6_l6', 'm6_l6_s04', 1, 3, TRUE, 0, FALSE),
  ('module6', 'm6_l6', 'm6_l6_s05', 1, 4, TRUE, 0, FALSE),
  ('module6', 'm6_l6', 'm6_l6_s06', 1, 5, TRUE, 0, FALSE),
  ('module6', 'm6_l6', 'm6_l6_s07', 1, 6, TRUE, 0, FALSE),
  ('module6', 'm6_l6', 'm6_l6_s08', 1, 7, TRUE, 0, FALSE),
  ('module6', 'm6_l6', 'm6_l6_s09', 1, 8, TRUE, 0, FALSE),
  ('module6', 'm6_l6', 'm6_l6_s10', 1, 9, TRUE, 0, FALSE),
  ('module6', 'm6_l6', 'm6_l6_s11', 1, 10, TRUE, 0, FALSE),
  ('module6', 'm6_l6', 'm6_l6_s12', 1, 11, FALSE, 0, TRUE),

  -- Lesson 6.7: Polynomial Playground (9 steps)
  ('module6', 'm6_l7', 'm6_l7_s01', 1, 0, FALSE, 0, FALSE),
  ('module6', 'm6_l7', 'm6_l7_s02', 1, 1, FALSE, 0, FALSE),
  ('module6', 'm6_l7', 'm6_l7_s03', 1, 2, FALSE, 0, FALSE),
  ('module6', 'm6_l7', 'm6_l7_s04', 1, 3, TRUE, 0, FALSE),
  ('module6', 'm6_l7', 'm6_l7_s05', 1, 4, TRUE, 0, FALSE),
  ('module6', 'm6_l7', 'm6_l7_s06', 1, 5, TRUE, 0, FALSE),
  ('module6', 'm6_l7', 'm6_l7_s07', 1, 6, TRUE, 0, FALSE),
  ('module6', 'm6_l7', 'm6_l7_s08', 1, 7, TRUE, 0, FALSE),
  ('module6', 'm6_l7', 'm6_l7_s09', 1, 8, FALSE, 0, TRUE)


ON CONFLICT (module_id, lesson_id, step_id, content_version)
DO UPDATE SET
  step_index = EXCLUDED.step_index,
  is_answer_step = EXCLUDED.is_answer_step,
  xp_reward = EXCLUDED.xp_reward,
  is_final = EXCLUDED.is_final;

-- PostgREST receives this after commit and refreshes its schema cache.
NOTIFY pgrst, 'reload schema';

COMMIT;
