-- Module 5 catalog extension for Lessons 5.1 through 5.6 (Linear Relationships).
-- Requires 202608120001_account_progress.sql. This migration is rerunnable.
--
-- xp_reward is 0 throughout: Algebrix no longer has a points economy, and the
-- column is retained only so the existing record_lesson_step RPC signature
-- stays untouched.

BEGIN;

DO $$
BEGIN
  IF to_regclass('public.learning_step_catalog') IS NULL THEN
    RAISE EXCEPTION
      'public.learning_step_catalog is required; apply 202608120001 first';
  END IF;

  IF to_regprocedure(
    'public.record_lesson_step(text,text,text,integer,boolean,integer)'
  ) IS NULL THEN
    RAISE EXCEPTION
      'public.record_lesson_step is required; apply 202608120001 first';
  END IF;
END;
$$;

-- Prevent concurrent catalog migrations from interleaving validation.
LOCK TABLE public.learning_step_catalog IN SHARE ROW EXCLUSIVE MODE;

-- Insert all step definitions for Module 5.
-- Generated by tool/generate_module_catalog_sql.dart from lib/data/module5/ so the
-- catalog cannot drift from the shipped lesson content.
INSERT INTO public.learning_step_catalog (
  module_id,
  lesson_id,
  step_id,
  content_version,
  step_index,
  is_answer_step,
  xp_reward,
  is_final
)
VALUES
  -- Lesson 5.1: Exploring the Coordinate Plane (11 steps)
  ('module5', 'm5_l1', 'm5_l1_s01', 1, 0, FALSE, 0, FALSE),
  ('module5', 'm5_l1', 'm5_l1_s02', 1, 1, FALSE, 0, FALSE),
  ('module5', 'm5_l1', 'm5_l1_s03', 1, 2, FALSE, 0, FALSE),
  ('module5', 'm5_l1', 'm5_l1_s04', 1, 3, FALSE, 0, FALSE),
  ('module5', 'm5_l1', 'm5_l1_s05', 1, 4, TRUE, 0, FALSE),
  ('module5', 'm5_l1', 'm5_l1_s06', 1, 5, FALSE, 0, FALSE),
  ('module5', 'm5_l1', 'm5_l1_s07', 1, 6, FALSE, 0, FALSE),
  ('module5', 'm5_l1', 'm5_l1_s08', 1, 7, TRUE, 0, FALSE),
  ('module5', 'm5_l1', 'm5_l1_s09', 1, 8, TRUE, 0, FALSE),
  ('module5', 'm5_l1', 'm5_l1_s10', 1, 9, TRUE, 0, FALSE),
  ('module5', 'm5_l1', 'm5_l1_s11', 1, 10, FALSE, 0, TRUE),

  -- Lesson 5.2: Discovering Slope (11 steps)
  ('module5', 'm5_l2', 'm5_l2_s01', 1, 0, FALSE, 0, FALSE),
  ('module5', 'm5_l2', 'm5_l2_s02', 1, 1, FALSE, 0, FALSE),
  ('module5', 'm5_l2', 'm5_l2_s03', 1, 2, FALSE, 0, FALSE),
  ('module5', 'm5_l2', 'm5_l2_s04', 1, 3, FALSE, 0, FALSE),
  ('module5', 'm5_l2', 'm5_l2_s05', 1, 4, TRUE, 0, FALSE),
  ('module5', 'm5_l2', 'm5_l2_s06', 1, 5, TRUE, 0, FALSE),
  ('module5', 'm5_l2', 'm5_l2_s07', 1, 6, FALSE, 0, FALSE),
  ('module5', 'm5_l2', 'm5_l2_s08', 1, 7, TRUE, 0, FALSE),
  ('module5', 'm5_l2', 'm5_l2_s09', 1, 8, FALSE, 0, FALSE),
  ('module5', 'm5_l2', 'm5_l2_s10', 1, 9, TRUE, 0, FALSE),
  ('module5', 'm5_l2', 'm5_l2_s11', 1, 10, FALSE, 0, TRUE),

  -- Lesson 5.3: Understanding Linear Relationships (8 steps)
  ('module5', 'm5_l3', 'm5_l3_s01', 1, 0, FALSE, 0, FALSE),
  ('module5', 'm5_l3', 'm5_l3_s02', 1, 1, FALSE, 0, FALSE),
  ('module5', 'm5_l3', 'm5_l3_s03', 1, 2, TRUE, 0, FALSE),
  ('module5', 'm5_l3', 'm5_l3_s04', 1, 3, FALSE, 0, FALSE),
  ('module5', 'm5_l3', 'm5_l3_s05', 1, 4, TRUE, 0, FALSE),
  ('module5', 'm5_l3', 'm5_l3_s06', 1, 5, FALSE, 0, FALSE),
  ('module5', 'm5_l3', 'm5_l3_s07', 1, 6, TRUE, 0, FALSE),
  ('module5', 'm5_l3', 'm5_l3_s08', 1, 7, FALSE, 0, TRUE),

  -- Lesson 5.4: Building Linear Equations (12 steps)
  ('module5', 'm5_l4', 'm5_l4_s01', 1, 0, FALSE, 0, FALSE),
  ('module5', 'm5_l4', 'm5_l4_s02', 1, 1, FALSE, 0, FALSE),
  ('module5', 'm5_l4', 'm5_l4_s03', 1, 2, FALSE, 0, FALSE),
  ('module5', 'm5_l4', 'm5_l4_s04', 1, 3, FALSE, 0, FALSE),
  ('module5', 'm5_l4', 'm5_l4_s05', 1, 4, FALSE, 0, FALSE),
  ('module5', 'm5_l4', 'm5_l4_s06', 1, 5, TRUE, 0, FALSE),
  ('module5', 'm5_l4', 'm5_l4_s07', 1, 6, TRUE, 0, FALSE),
  ('module5', 'm5_l4', 'm5_l4_s08', 1, 7, FALSE, 0, FALSE),
  ('module5', 'm5_l4', 'm5_l4_s09', 1, 8, TRUE, 0, FALSE),
  ('module5', 'm5_l4', 'm5_l4_s10', 1, 9, FALSE, 0, FALSE),
  ('module5', 'm5_l4', 'm5_l4_s11', 1, 10, TRUE, 0, FALSE),
  ('module5', 'm5_l4', 'm5_l4_s12', 1, 11, FALSE, 0, TRUE),

  -- Lesson 5.5: Graphing Linear Equations (8 steps)
  ('module5', 'm5_l5', 'm5_l5_s01', 1, 0, FALSE, 0, FALSE),
  ('module5', 'm5_l5', 'm5_l5_s02', 1, 1, FALSE, 0, FALSE),
  ('module5', 'm5_l5', 'm5_l5_s03', 1, 2, FALSE, 0, FALSE),
  ('module5', 'm5_l5', 'm5_l5_s04', 1, 3, TRUE, 0, FALSE),
  ('module5', 'm5_l5', 'm5_l5_s05', 1, 4, FALSE, 0, FALSE),
  ('module5', 'm5_l5', 'm5_l5_s06', 1, 5, TRUE, 0, FALSE),
  ('module5', 'm5_l5', 'm5_l5_s07', 1, 6, TRUE, 0, FALSE),
  ('module5', 'm5_l5', 'm5_l5_s08', 1, 7, FALSE, 0, TRUE),

  -- Lesson 5.6: Reading Linear Graphs (8 steps)
  ('module5', 'm5_l6', 'm5_l6_s01', 1, 0, FALSE, 0, FALSE),
  ('module5', 'm5_l6', 'm5_l6_s02', 1, 1, FALSE, 0, FALSE),
  ('module5', 'm5_l6', 'm5_l6_s03', 1, 2, FALSE, 0, FALSE),
  ('module5', 'm5_l6', 'm5_l6_s04', 1, 3, TRUE, 0, FALSE),
  ('module5', 'm5_l6', 'm5_l6_s05', 1, 4, TRUE, 0, FALSE),
  ('module5', 'm5_l6', 'm5_l6_s06', 1, 5, TRUE, 0, FALSE),
  ('module5', 'm5_l6', 'm5_l6_s07', 1, 6, TRUE, 0, FALSE),
  ('module5', 'm5_l6', 'm5_l6_s08', 1, 7, FALSE, 0, TRUE)


ON CONFLICT (module_id, lesson_id, step_id, content_version)
DO UPDATE SET
  step_index = EXCLUDED.step_index,
  is_answer_step = EXCLUDED.is_answer_step,
  xp_reward = EXCLUDED.xp_reward,
  is_final = EXCLUDED.is_final;

-- PostgREST receives this after commit and refreshes its schema cache.
NOTIFY pgrst, 'reload schema';

COMMIT;
